<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyName>EnigmaBenchmarkAvalonia</AssemblyName>
    <RootNamespace>EnigmaBenchmarkAvalonia</RootNamespace>
    <TieredCompilation>true</TieredCompilation>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Shaders\*.sksl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia"                   Version="11.3.13" />
    <PackageReference Include="Avalonia.Desktop"           Version="11.3.13" />
    <PackageReference Include="Avalonia.Themes.Fluent"     Version="11.3.13" />
    <PackageReference Include="Avalonia.Fonts.Inter"       Version="11.3.13" />
    <PackageReference Include="SkiaSharp"                  Version="3.119.3-preview.1.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.3-preview.1.1" />
  </ItemGroup>
</Project>
